### ISSUE TITLE
yarn error

### ISSUE THREAD

**Issue by matteha** [neoclide/coc-python#1]
Getting a yarn pkg error here, when trying:

:CocInstall coc-python

 Do you know if it's already on there? Thanks for this, very exciting!

**Comment by chemzqm** [comment]
It's not working.

**Comment by matteha** [comment]
I see. Thank you for the reply. Do you have an estimate of when it could work? Like days, weeks?Thanks!

**Comment by chemzqm** [comment]
Should be in a week，but it's expected to have some bugs at the begining.

**Comment by chemzqm** [comment]
It's working now, you can test it with master of coc.nvim.
