### ISSUE TITLE
Cannot update MSLP.

### ISSUE THREAD

**Issue by AllenDang** [neoclide/coc-python#102]
With a python file open, after invoke update mslp, i got following error msg:

Command error: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.4.63:80 - Local (172.18.130.38:50191)

**Comment by fannheyward** [comment]
Looks like you are using a proxy, but which is failed to server. Please make sure your proxy is works.

**Comment by AllenDang** [comment]
Oh, yes. It works after I remove the proxy setting. Thanks!
