### ISSUE TITLE
Cannot show documentation

### ISSUE THREAD

**Issue by ecly** [neoclide/coc-python#103]
I've recently begun adopting Coc, and have ran into one annoyance for my python workflow, which I suspect might be a user error on my part.

I use the default configuration supplied from Coc, meaning I have:
```bash
" Use K to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>
```
in my configuration. When I try to press `K`, I receive the error:
```
E117: Unknown function: jedi#show_documentation
```

I can however do `:python import jedi` without any troubles. Is this not supported or am I doing something wrong.

**Comment by chemzqm** [comment]
Check your keymap be verbose imap command
