### ISSUE TITLE
Timeout when installing

### ISSUE THREAD

**Issue by zrc951205** [neoclide/coc-python#111]
I'm trying to install coc-python on nvim 0.4.2, Centos7.6. And it's a remote server which need set proxy to connet to internet. I've set http_proxy, https_proxy and ftp_proxy on ~/.bash_profile, and try `npm config proxy=xxxxx:xx`. 

But when I run the installing command
`CocInstall coc-python`
it returns:
`[coc.nvim] Error on install coc-python: Error: connect ETIMEDOUT 104.16.16.35:443`

Is there any way to set the proxy properly or install the extension manually or by vim-plug?

**Comment by chemzqm** [comment]
Check your `$HTTP_PROXY` and `$HTTPS_PROXY`

**Comment by chemzqm** [comment]
shou
