### ISSUE TITLE
:CocInstall coc-python fails

### ISSUE THREAD

**Issue by kblcuk** [neoclide/coc-python#119]
...because it tries to download package from GitHub package registry, but there isn't one :thinking: 
I'm not actually sure if this relates to this repo, or https://github.com/neoclide/coc.nvim in general (since some other packages also seem to be missing, for instance coc-json):
```
[coc.nvim] Error on install coc-json: Error: Invalid response from https://npm.pkg.github.com/coc-json: 404
```

**Comment by fannheyward** [comment]
You can use npmjs registry. All extensions are published on npmjs only.

**Comment by chemzqm** [comment]
Checkout your `.npmrc`

**Comment by chemzqm** [comment]
Looks like we need support custom arguments for `install` and `update` extensions from npm.

**Comment by kblcuk** [comment]
M-okay, but what if my project uses github packages :/ Well, I guess I'll just launch vim outside of it...
