### ISSUE TITLE
Have installed, but unable to add configuration file

### ISSUE THREAD

**Issue by esn89** [neoclide/coc-python#12]
An error I am getting with :CocConfig trying to add the settings is this:
https://i.imgur.com/bRz7FME.png

Am I adding it in the right place, or is it a separate configuration file?

Thank you.

**Comment by chemzqm** [comment]
Should be failed to load the extension, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim for log.

**Comment by esn89** [comment]
Yes, you're correct, it did fail to load the extension.  I have followed your advice and set the: 
```export NVIM_COC_LOG_LEVEL=debug```
Thank you for showing me.  Now I found the log:
[pastebin log](https://pastebin.com/Z111iGvG)

All the language servers themselves loaded, even MPLS, but I do not see any word of python.

**Comment by chemzqm** [comment]
/snapshot/coc.nvim/lib/util/factory.js:67:32)
means you're using binary release.

**Comment by esn89** [comment]
So I need which version of coc.nvim?  Or is it the wrong version of coc-python?

**Comment by chemzqm** [comment]
Use master https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-to-use-cocnvim-from-master-branch

**Comment by esn89** [comment]
Thank you, you are amazing, @chemzqm.  It works!

**Comment by karambaq** [comment]
@esn89 Sorry for the offtop, but can you share your vim config? It looks beautiful.

**Comment by esn89** [comment]
Sure, here is:  https://we.tl/t-9aBExghbIM it is a zip containing my .vim files.
If you are interested in the statusline it is also there, but you need a patched font here: https://github.com/ryanoasis/nerd-fonts namely the powerline and fontawesome

**Comment by karambaq** [comment]
@esn89 Great, thank you a lot! And also can you please share your coc-settings.json? I really like those icons and have troubles with setting up python LS. Thank in advance!

**Comment by esn89** [comment]
@karambaq Hi.  You're welcome, here is my coc-settings.json. https://pastebin.com/x4Tfw7cZ
