### ISSUE TITLE
not showing packages installed from conda enviroment

### ISSUE THREAD

**Issue by ahmedselim2017** [neoclide/coc-python#123]
## versions

vim version: NVIM v0.4.3
node version: v10.16.3
coc.nvim version: 0.0.74-377c2729b9
term: xterm-256color
platform: linux

## Output channel: Python
Starting Jedi Python language engine.
##########Linting Output - pylint##########
************* Module main
1,0,error,E0401:Unable to import 'pandas' (import-error)

--------------------------------------------------------------------
Your code has been rated at -2.50/10 (previous run: -2.50/10, +0.00)

## Describe the bug

Coc.nvim says unable to import pandas even if I installed using Conda.

## Reproduce the bug

- Create and activate a new Conda environment with
```shell
conda create --name ai-all
conda activate ai-all
```
- Install some packages using conda
```shell
conda install keras
```
- Start Neovim via using normal configs which works without anaconda

- Import some packages which installed by conda

## Screenshots (optional)

![sc](https://user-images.githubusercontent.com/28633984/69913811-f85b6d00-144d-11ea-8d1f-92134f75f660.png)

**Comment by DoktorMike** [comment]
I have the same issue and indeed it works when calling `:CocCommand python.setInterpreter` but to me that seems a little bit silly since the conda environment has already been set before I start nvim. Isn't there a way to make the setInterpreter choose the first python available (which would correspond to the one currently active in conda)?

**Comment by oblitum** [comment]
@DoktorMike this is issue #55.

**Comment by astier** [comment]
Same issue #89 would be great if coc-python would inherit the environment from the activated conda environment.

**Comment by oblitum** [comment]
I'm not sure what you use for environment auto activation, I use pyenv (that integrates nicely with conda), and for it, auto activation also seems an issue on vscode-python, from which coc-python forked:

* https://github.com/microsoft/vscode-python/issues/1167

**Comment by ahmedselim2017** [comment]
> I think this issue should have been opened on coc-python instead. Still, did you select the right python environment from `:CocCommand python.setInterpreter`? I use coc-python with conda without issues.

When I do that I get this error:
```[coc.nvim] Jedi error: Cannot call write after a stream was destroyed```

**Comment by oblitum** [comment]
@ahmedselim2017 please close issue then.
