### ISSUE TITLE
[Q] CocCommand python.setInterpreter

### ISSUE THREAD

**Issue by yujinyuz** [neoclide/coc-python#127]
I've been searching for some workarounds on how to make neovim autocomplete support virtualenvs by creating a `.vim/coc-settings.json` inside my project directory. But this seems quite tedious for me.

Is there any way that after calling `:CocCommand python.setInterperter`, it would automatically create the `.vim/coc-settings.json` file for me with the settings:

```json
{
    "python.pythonPath": "/Users/me/.virtualenvs/amazing/bin/python"
}
```

Side Question:
Every time Vim is restarted, I'm getting this message

```
⠦ Analyzing in background, 115 items left... Python 3.6.8 64-bit ('amazing': virtualenv)
```

Is this normal? Would there be a way to somehow cache this? I have to wait for it to finish before making the autocomplete work

VSCode doesn't seem to re-analyze the virtualenvs when restarting them

**Comment by you-n-g** [comment]
@yujinyuz  I have found similar problem.   #197 
How did you  solve it ?

**Comment by yujinyuz** [comment]
@you-n-g I forgot what I did. You can check my coc-settings.json here: https://github.com/yujinyuz/dotfiles/blob/master/vim/coc-settings.json

And it seems that my current settings (coc and vimrc) already caches virtualenvs

**Comment by you-n-g** [comment]
@yujinyuz  thanks.

**Comment by geo7** [comment]
@yujinyuz that link is dead - is the file anywhere else?

**Comment by yujinyuz** [comment]
@geo7 I've updated the link

https://github.com/yujinyuz/dotfiles-old/blob/master/vim/coc-settings.json
