### ISSUE TITLE
How do you enable mutiple linters?

### ISSUE THREAD

**Issue by cubetastic33** [neoclide/coc-python#133]
The README says this:
> To enable multiple linters, edit the configuration file instead of use `python.setLinter` command.

But I can't figure out what option to actually set. I want pylint and flake8, so I tried setting `python.linting.flake8Enabled` to `true` after pylint was already enabled, and both `pylint` and `flake8` are installed and work separately, but this did not enable flake8.

**Comment by chemzqm** [comment]
You have to enable flake8 and pylint in `.vim/coc-settings.json` inside your project root.

**Comment by cubetastic33** [comment]
Ohh, okay. Is it fine if I just delete the `.vim` directory in the project's root and add it instead to `~/.config/nvim/coc-settings.json`?

**Comment by chemzqm** [comment]
Sure, if you want to enable them for all your projects.

**Comment by raph90** [comment]
This doesn't seem to be fixed. I have this in my coc-config: 
```
  "python.linting.pylintEnabled": true,
  "python.linting.mypyEnabled": true,
```
Still, only pyLint is being used. I can do a coc command and set the linter to mypy, but then only the one linter works.
