### ISSUE TITLE
linter turned off when python.jediEnabled is set to false

### ISSUE THREAD

**Issue by matteha** [neoclide/coc-python#14]
Putting   

"python.jediEnabled": false

 in coc-settings.json (to enable Intellisense, since it is disabled by default in favor of jedi) seems to disable the linter, even when

  "python.linting.enabled": true,
  "python.linting.pylintEnabled": true,

are in coc-settings.json as well.

A similar problem for vscode itself is reported here:

https://github.com/Microsoft/vscode-python/issues/3292

Do you know whether this is fixable for coc-python?

Thanks again!

**Comment by matteha** [comment]
Relatedly, the linter only seems to work once files are :w in vim, is it possible to lint 'on the spot'?

Using flake8, see, it doesn't mention the top STOP unless I :w the file:

<img width="196" alt="Screen Shot 2019-03-27 at 4 39 23 PM" src="https://user-images.githubusercontent.com/36545991/55110707-fe26d480-50ae-11e9-8290-66619d38e84c.png">

**Comment by esn89** [comment]
@matteha 

I notice the same thing as well, I thought the linting was async and no :w was needed.

**Comment by chemzqm** [comment]
MPLS requries saved file to run diagnostic, that's because VSCode always create file before edit.

**Comment by esn89** [comment]
However, flake8/pylint is separate from MPLS though.  Does that mean MPLS is blocking it?

**Comment by chemzqm** [comment]
@esn89 When your're using MPLS, the linting is done by MPLS instead of flake8 & pylint.

**Comment by esn89** [comment]
aaah, i see.  so it gets "stolen" and there is no way to turn off MPLS linting?

**Comment by chemzqm** [comment]
>  there is no way to turn off MPLS linting?

There're settings.

**Comment by lkhphuc** [comment]
I currently do not use Language server (`"python.jediEnabled": true`) but linter also only update when `:w`.
Did I miss anything?

**Comment by chemzqm** [comment]
When you have `"python.jediEnabled": false`, MPLS is used instead of python files, so `python.linting.enabled` which only has affect when python files are enabled would not works.

To disable diagnostics of MPLS, you need add codes to `"python.analysis.disabled"` array.

**Comment by avalonv** [comment]
@chemzqm  so to clarify, if I'm using `coc-python` and I want linting to happen automatically, without having to write the buffer first, I need to add the following to my `coc-settings.json`:

```
    "python.analysis.diagnosticEnabled": false,
    "python.linting.enabled": true,
    "python.jediEnabled": true,
```
?

**Comment by Mikkolehtimaki** [comment]
So to clarify, there is no linting possible when MPLS is used? I have now
```
   "python.analysis.diagnosticEnabled": true,
    "python.linting.enabled": true,
    "python.jediEnabled": false
```
and I would like linting to happen without Jedi. Is that possible?

**Comment by esn89** [comment]
There is linting possible when MPLS is used, but not as-you-type.  The only way is on save.  Unless someone managed to get linting without saving, please tell me :D

**Comment by Mikkolehtimaki** [comment]
> There is linting possible when MPLS is used, but not as-you-type. The only way is on save. Unless someone managed to get linting without saving, please tell me :D

I'd be happy to have it working even on saving. Could you share a working config?

**Comment by esn89** [comment]
Sure thing:
https://pastebin.com/QyHrk5A7

**Comment by Mikkolehtimaki** [comment]
Thanks a bunch! I was missing some settings. Pylint now shows messages in location list, however it finds a considerably smaller amount of errors than ALE for example. With your settings I also got formatting on save working! Do you know if it is possible to have formatting messages also in the location list or side bar?

**Comment by esn89** [comment]
Glad to hear that.  The messages such as "Line char more than 80" will not appear on the side.
You can have a little font-icon by the gutter though, here's mine for example:

https://i.imgur.com/INBytwp.png

**Comment by avalonv** [comment]
@esn89 
I still use `coc-pyls` which is deprecated but at least works as you type

**Comment by pkout** [comment]
For me, PyLint linting started working only once I had these settings in my `coc-settings..json`

```
{
    "eslint.options": {
        "configFile": ".eslintrc.json"
    },
    "python.analysis.diagnosticEnabled": true,
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": true,
    "python.jediEnabled": false
}
```
