### ISSUE TITLE
Jump To Definition doesn't work on types enclosed by quotes

### ISSUE THREAD

**Issue by davafons** [neoclide/coc-python#151]
If you try to do Jump To Definition on a type that is enclosed by quotes, coc will throw a `[coc.nvim] Definition not found` error message.

Example that __doesn't work__:
```
def fun(foo: "Foo"):
	...
``` 

Otherwise, if the type __isn't enclosed__, the Jump To Definition will work as expected.

Example that __works__:
```
def fun(foo: Foo):
	...
```

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
