### ISSUE TITLE
Expand variables in path configuration

### ISSUE THREAD

**Issue by ChuckDaniels87** [neoclide/coc-python#159]
I was wondering if it would be possible to implement environment variable expansion (such as `$HOME`) in coc-python settings. An example would be setting Black or PyLint paths to local/global install:
```json

"python.formatting.blackPath": "$HOME/.local/bin/black",
"python.linting.pylintPath": "$HOME/.local/bin/pylint"
```
Right now, this is being resolved as a relative path to the current project, not expanding the `$HOME` env variable (`/path/to/project/$HOME/.local/bin/black` and not `/home/user/.local/bin/black`).

Alternatively, lookup of linters and fomatters could fall back to `$PATH` if they are not present in the current virtualenv. Thus, they would be found at `$HOME/.local/bin`, `/usr/local/bin` or `/usr/bin/` if they are installed in the system. This will avoid polluting the current project with additional packages in the case of using Poetry or Pipenv.

I see the second solution to be really practical in several use cases but don't know if it would be out of the scope of `coc-python`. I would gladly try to contribute to develop any of them.

**Comment by chemzqm** [comment]
Use `coc#config()` instead.

**Comment by ChuckDaniels87** [comment]
@chemzqm Thank you very much! It works like a charm. Congrats for this great project.

For the record, if someone had this problem I solved it adding these lines in my `init.vim`:
```vim
let local_bin_path = $HOME . "/.local/bin/"
call coc#config("python.linting.pylintPath", local_bin_path . "pylint")
call coc#config("python.linting.flake8Path", local_bin_path . "flake8")
call coc#config("python.linting.pydocstylePath", local_bin_path . "pydocstyle")
call coc#config("python.linting.blackPath", local_bin_path . "black")
```
