### ISSUE TITLE
Don't automatically put python.pythonPath into coc-settings.json

### ISSUE THREAD

**Issue by mike-hearn** [neoclide/coc-python#16]
Hi chemzqm, first of all thank you so much for coc.nvim. It's improved my entire vim experience.

Here's my issue:

I work on a bunch of different python projects — some have their own virtual environment, some just work in the global/system Python space. One project specifically causes coc to automatically add this line into `coc-settings.json`:

```
"python.pythonPath": ".venv/bin/python3"
```

The problem is that venv path is not universal for all my projects, and once that line has been added to `coc-settings.json`, it causes my other projects with different python paths to pop up the `No Python interpreter is selected` prompt.

Is there a way to prevent automatically writing `python.pythonPath` into the config file, and just use the current `python` that exists in `$PATH`?

**Comment by chemzqm** [comment]
It should update workspace settings, but we don't have workspace like VSCode.

**Comment by mike-hearn** [comment]
That makes sense. I guess my larger question is whether there can potentially be a setting that FORCES it to always use the `python` in the PATH. I tried to manually set `"python.pythonPath": "python"` but that setting also gets overwritten with `.venv/bin/python3` if I open a file within that specific project.

**Comment by chemzqm** [comment]
Will remove the automatic update of user settings.

**Comment by chemzqm** [comment]
It's bug of coc.nvim, just fixed.
