### ISSUE TITLE
How to refactor-rename using rope?

### ISSUE THREAD

**Issue by madhukar93** [neoclide/coc-python#162]
I have rope installed, but I don't see rename among actions
<img width="401" alt="image" src="https://user-images.githubusercontent.com/7714050/78295988-98371d80-754a-11ea-9008-1eb79429e1f6.png">

```
:echo CocHasProvider('rename')
v:true
```

**Comment by chemzqm** [comment]
Read readme of coc.nvim

**Comment by madhukar93** [comment]
sorry about that, I missed it somehow

**Comment by madhukar93** [comment]
sorry I missed it, didn't understand all the <Plug> mappings :crying_cat_face:
