### ISSUE TITLE
Sort imports on save

### ISSUE THREAD

**Issue by Rizhiy** [neoclide/coc-python#163]
Is there an option to sort imports on save, similar to format on save?
If not, would be nice to add it.

**Comment by chemzqm** [comment]
No, You have to create a autocmd yourself.

**Comment by lsaint** [comment]
what's the command to sort import?

> Sorting import statements (use the Python: Sort Imports command)

this command in doc didn't work.

**Comment by chemzqm** [comment]
> i need to save it another time to take effect.

Hm, it should not.
My advice is never use it on save, it has side effect and could change all your buffers.

**Comment by cristicbz** [comment]
@chemzqm *sorting* imports doesn't have side effects, right? only *organizing* i.e removing unused imports would
