### ISSUE TITLE
pyright linter support

### ISSUE THREAD

**Issue by jen6** [neoclide/coc-python#165]
Hi
I know the coc-pyright exists but it cannot use both the coc-python and the coc-pyright.
Is there any way to use the pyright linting in the coc-python?

**Comment by chemzqm** [comment]
Nope

**Comment by Congee** [comment]
It is possible to disable completion/hover from `coc-python`? This feature is desired, because I find `coc-pyright` offers much better type inference than `coc-python`. It would be nice to use the linting functionality from `coc-python` and completion from `coc-pyright`

**Comment by eelkeh** [comment]
Seconded, it would be great to just have the option to disable completions
