### ISSUE TITLE
Rename/refactor not working

### ISSUE THREAD

**Issue by GaetanLepage** [neoclide/coc-python#167]
Hello !

When I try to use the rename functionality, nothing happens.

- Rope python package is installed
- The interpreter is the good one
- I use MPLS (not jedi)... not sure if this matters or not...

When I press the key which is mapped to `coc-rename`, it asks me to change the name of the variable (as expected). But, once I press enter, nothing happens: no error, no modification...

Thanks in advance :)

**Comment by derekschrock** [comment]
Possible dup of #139

**Comment by GaetanLepage** [comment]
Actually, I has rope installed and was using MPLS (and not Jedi). This is why I thought useful to open a separate issue.
For a strange reason, it is now working.

I am closing the issue.
