### ISSUE TITLE
coc-python is not finding Black linter

### ISSUE THREAD

**Issue by bearcatsandor** [neoclide/coc-python#173]
Linux jaguarundi 5.5.10-gentoo #2 SMP Sat Mar 21 15:50:01 MDT 2020 x86_64 AMD Ryzen 7 2700 Eight-Core Processor AuthenticAMD GNU/Linux

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  8 2020 13:12:42)
node version: v13.12.0
coc.nvim version: 0.0.78-fc983ce6dd
term: dumb
platform: linux

Whenever I open or save a python file, I get a popup from coc-python asking me to choose a linter.

In my coc-settings.json I have:

"python.formatting.provider": "black",
"python.formatting.blackPath": "/home/moonwind/.local/bin/black",

but it should just find it since /home/moonwind/.local/bin/ is in my PATH envar and 'black' runs at my terminal.

:cocinfo tells me:
Starting Jedi Python language engine.
Linter 'pylint' is not installed. Please install it or select another linter".
10 Error: Module 'pylint' not installed.

I have jedi 0.15.2  installed via Gentoo portage. I do not have the jedi vim plugin installed.

**Comment by lamcw** [comment]
Try adding `"python.linting.pylintEnabled": false` in `coc-settings.json`?

**Comment by bearcatsandor** [comment]
Thank you! That worked!
