### ISSUE TITLE
Jedi version 0.17.1 too old, requires >= 0.17.0

### ISSUE THREAD

**Issue by joemrt** [neoclide/coc-python#186]
Since coc-python upgraded this morning, I am getting the following error whenever I try to follow a definition
```
[coc.nvim] Jedi error:     raise RuntimeError("Jedi version %s too old, requires >= 0.17.0" % (j
edi.__version__))
RuntimeError: Jedi version 0.17.1 too old, requires >= 0.17.0
```
which is obviously nonsense. I am getting a similar same error with jedi in version 0.17.0.

**Comment by joemrt** [comment]
Can confirm that pull request #184 might fix this. Changed the corresponding line in pythonFiles/completion.py and it seems to work at the moment.

**Comment by kuznero** [comment]
I have it like this too: `Jedi version 0.17.0 too old, requires >= 0.17.0`

**Comment by Raysuner** [comment]
> I have it like this too: `Jedi version 0.17.0 too old, requires >= 0.17.0`
have you solve it now? i have the same problem now

**Comment by Raysuner** [comment]
> > I have it like this too: `Jedi version 0.17.0 too old, requires >= 0.17.0`
> > have you solve it now? i have the same problem now

I have solve this problem, just upgrade coc-python to 1.2.12
``` bash
:CocInstall coc-python@1.2.12
```

**Comment by tgkei** [comment]
It's not working

**Comment by GianniGi** [comment]
not working either

**Comment by tgkei** [comment]
> It's not working

I don't know it will work to everyone, in my case, I just simply upgraded ```Jedi``` and it works. Command was ```pip install --upgrade jedi```. I hopes it helps.

**Comment by GianniGi** [comment]
Thanks for the suggestion, meanwhile I installed the latest python and now
it works

Il giorno mercoledì 2 settembre 2020, Tae Gyun Kim <notifications@github.com>
ha scritto:

**Comment by Himon-SYNCRAFT** [comment]
I had the same problem. I am using virtualenv so for me solution was to update jedi in virtual environment of my project instead of globally installed one.
