### ISSUE TITLE
Duplicate auto-complete items MPLS

### ISSUE THREAD

**Issue by matteha** [neoclide/coc-python#19]
The auto complete items tend to duplicate sometimes, is there a reason for this / way to disable this? Using the MPLS auto complete.

<img width="125" alt="Screen Shot 2019-03-28 at 11 16 02 AM" src="https://user-images.githubusercontent.com/36545991/55169381-15b39b00-514b-11e9-92df-11ab3dc58b04.png">

**Comment by chemzqm** [comment]
Please upload the output log https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel, so I can check whether they can be merged.

**Comment by chemzqm** [comment]
Looks like you're also using other completion sources for python completion.
