### ISSUE TITLE
Extreme slow when editing a python file in a big folder mounted by ssh.

### ISSUE THREAD

**Issue by szsdk** [neoclide/coc-python#190]
I mounted an ssh netdisk and tried to edit python files in that folder. Then I found the coc-python kept showing "searching interpreter" in the status bar. Inputting may be okay (sometimes I need to wait like a half min to type one letter. Right, I call it okay), but I almost cannot do anything else like `:CocCommand` or even `:w`. They took forever. Due to this slowness, I can not dig deeper into this problem by myself. Could you share some advice?

**Comment by chemzqm** [comment]
Use `python.pythonPath` in local configuartion file by `:CocLocalConfig` command.

**Comment by szsdk** [comment]
Thanks for a quick reply. But it seems not working. Maybe, I did something wrong.
This is my local `.vim/coc-settings.json`:
```json
{
    "python.pythonPath": "/home/sss/miniconda3/bin/python"
}
```
I excepted that setting tells `coc-python` to use the python I pointed out and skipped the searching interpreter step, but it did not work and still kept searching an interpreter.  Maybe, there is a conflict between local and global configure. This is the global config json
```
{
  "languageserver": {
    "ccls": {
      "command": "ccls",
      "filetypes": ["c", "cpp", "objc", "objcpp", "cuda"],
      "rootPatterns": [".ccls", "compile_commands.json",  ".vim/", ".git/", ".hg/"],
      "initializationOptions": {
         "cache": {
           "directory": "/tmp/ccls"
         }
       }
    }
  },
  "python.linting.enabled": true,
  "python.linting.pylintArgs": ["--rcfile", "~/.pylintrc", "-d", "C0411"],
  "python.formatting.provider": "black",
  "python.linting.pylintUseMinimalCheckers": false,
  "python.sortImports.args": ["-sp", "~/.isort.cfg"],
  "coc.preferences.formatOnSaveFiletypes": ["*.py"],
  "snippets.ultisnips.directories": [
      "UltiSnips",
      "~/dotfiles/UltiSnips/"
  ]
}
```

**Comment by chemzqm** [comment]
The language server need index all your files, so my suggest not use mounted folder，instead and configure your vim on remote server instead

**Comment by szsdk** [comment]
Hi, then I have one following question: is it possible to take advantage of the `.gitignore` file to guide this indexing process? Now all my data files are in another subfolders and managed by `.gitignore`.

**Comment by chemzqm** [comment]
>  take advantage of the .gitignore file to guide this indexing process? 

No, as far as I know, no language server would respect that file, some servers could provide options for index files, but not coc-python.
