### ISSUE TITLE
coc-python not working ModuleNotFoundError

### ISSUE THREAD

**Issue by unihernandez22** [neoclide/coc-python#193]
I've installed coc-python and when I out any character it shows the following error:
```
[coc.nvim] error:     at Pipe.onread (net.js:628:25)
source jedi timeout after 5000ms
[coc.nvim] Jedi error:     import jedi
ModuleNotFoundError: No module named 'jedi'
```

But I have installed jedi too

**Comment by unihernandez22** [comment]
It was an `coc-settings.json` error

**Comment by neel229** [comment]
> It was a `coc-settings.json` error

What was the solution because I'm facing similar error

**Comment by meinzer1899** [comment]
I would also appreciate a solution here.
@neel229 Did you solve the problem already?

**Comment by unihernandez22** [comment]
> I would also appreciate a solution here.

Add `"python.pythonPath": "python3"` to your coc-settings.json file

**Comment by meinzer1899** [comment]
Thanks @unihernandez22. I want the language server to find the interpreter automatically.

I found a solution in this post https://github.com/palantir/python-language-server/issues/543.
By deactivating jedi in the CocConfig, coc automatically installs and uses MS Python Language 

For people who want to use Jedi, you have to set it's path accordingly. See this solution https://github.com/neoclide/coc-python/issues/40

**Comment by RedoC-github** [comment]
Wow! I'm very happy.
I gave up vim almost because of this problem.

Very thank you, and thank you 👍
