### ISSUE TITLE
ENOENT error Unhandle Rejection

### ISSUE THREAD

**Issue by matteha** [neoclide/coc-python#2]
Hello,

Fantastic that you made this! Just ran the CoC Install, and got this error, do you know how to fix this?Thanks!

extension coc-python installed!
[coc.nvim] Error loading extension from /Users/admin/.config/coc/extensions/node_modules/coc-python/lib/index.js: (intermediate value).disable(...).ignoreErrors is not a function
[vim-node-coc]: UnhandledRejection: ENOENT: no such file or directory, rename '/Users/admin/.config/coc/extensions/node_modules/coc-python/out/client/debugger/debugAdapter/main.js.map' -> '/Users/admin/.c
onfig/coc/extensions/node_modules/coc-python/out/client/debugger/debugAdapter/main.js.map.disabled'
Error: ENOENT: no such file or directory, rename '/Users/admin/.config/coc/extensions/node_modules/coc-python/out/client/debugger/debugAdapter/main.js.map' -> '/Users/admin/.config/coc/extensions/node_mod
ules/coc-python/out/client/debugger/debugAdapter/main.js.map.disabled'
[coc.nvim] Extension coc-python not found!
[coc.nvim] Extension coc-python not found!
extension coc-python installed!
[coc.nvim] Error loading extension from /Users/admin/.config/coc/extensions/node_modules/coc-python/lib/index.js: (intermediate value).disable(...).ignoreErrors is not a function
[vim-node-coc]: UnhandledRejection: ENOENT: no such file or directory, rename '/Users/admin/.config/coc/extensions/node_modules/coc-python/lib/index.js.map' -> '/Users/admin/.config/coc/extensions/node_mo
dules/coc-python/lib/index.js.map.disabled'
Error: ENOENT: no such file or directory, rename '/Users/admin/.config/coc/extensions/node_modules/coc-python/lib/index.js.map' -> '/Users/admin/.config/coc/extensions/node_modules/coc-python/lib/index.js
.map.disabled'

**Comment by matteha** [comment]
This is my CocInfo by the way:

                                                                                                     │## versions
~                                                                                                    │
~                                                                                                    │vim version: NVIM v0.4.0-dev
~                                                                                                    │node version: v8.9.0
~                                                                                                    │coc.nvim version: 0.0.62
~                                                                                                    │term: iTerm.app
~                                                                                                    │platform: darwin
~                                                                                                    │
~                                                                                                    │## Error messages
~                                                                                                    │UnhandledRejection: ENOENT: no such file or directory, rename '/Users/admin/.config/coc/extensions/nod
~                                                                                                    │e_modules/coc-python/out/client/debugger/debugAdapter/main.js.map' -> '/Users/admin/.config/coc/extens
~                                                                                                    │ions/node_modules/coc-python/out/client/debugger/debugAdapter/main.js.map.disabled'
~                                                                                                    │Error: ENOENT: no such file or directory, rename '/Users/admin/.config/coc/extensions/node_modules/coc
~                                                                                                    │-python/out/client/debugger/debugAdapter/main.js.map' -> '/Users/admin/.config/coc/extensions/node_mod
~                                                                                                    │ules/coc-python/out/client/debugger/debugAdapter/main.js.map.disabled'
~                                                                                                    │UnhandledRejection: ENOENT: no such file or directory, rename '/Users/admin/.config/coc/extensions/nod
~                                                                                                    │e_modules/coc-python/out/client/debugger/debugAdapter/main.js.map' -> '/Users/admin/.config/coc/extens
~                                                                                                    │ions/node_modules/coc-python/out/client/debugger/debugAdapter/main.js.map.disabled'
~                                                                                                    │Error: ENOENT: no such file or directory, rename '/Users/admin/.config/coc/extensions/node_modules/coc
~                                                                                                    │-python/out/client/debugger/debugAdapter/main.js.map' -> '/Users/admin/.config/coc/extensions/node_mod
~                                                                                                    │ules/coc-python/out/client/debugger/debugAdapter/main.js.map.disabled'
~                                                                                                    │

**Comment by chemzqm** [comment]
It's fixed, upgrade coc.nvim and coc-python requried.

**Comment by matteha** [comment]
Hello,

Thanks! I upgraded both, but now get this error:

[coc.nvim] Error loading extension from /Users/admin/.config/coc/extensions/node_modules/coc-python/lib/index.js: Reflect.hasOwnMetadata is not a function

**Comment by chemzqm** [comment]
You need to build from master instead of use binary release.

**Comment by chemzqm** [comment]
Use `Plug 'neoclide/coc.nvim', { 'do': 'yarn install --frozen-lockfile'}` as `Plug` command of vim-plug and reinstall coc.nvim.
