### ISSUE TITLE
Interpreter keep switching to global one

### ISSUE THREAD

**Issue by ntcong** [neoclide/coc-python#20]
I'm using this minimal vimrc
```
set runtimepath+=~/.vim
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'do': 'yarn install'}
Plug 'honza/vim-snippets'
call plug#end()
let g:coc_snippet_next = '<TAB>'
let g:coc_snippet_prev = '<S-TAB>'
 let g:coc_global_extensions =['coc-snippets','coc-json']
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
```
Starting it inside a virtualenv called "buxbot" and `vi -u mini.vim`
Running `:CocCommand` -> `Select Interpreter`
```
Select pythonPath, current: /usr/local/opt/python/bin/python3.7:
1. /usr/bin/python
2. /usr/local/bin/python
3. /usr/local/opt/python@2/bin/python2.7
4. /Users/user/.virtualenvs/buxbot/bin/python
5. /usr/local/bin/python3
```
After choosing 4 and run CocCommand again,
```
Select pythonPath, current: /usr/local/opt/python/bin/python3.7:
```

Also I think it should choose the current python (which is the virtualenv) by default.

I'm using `NVIM v0.3.4` on MacOS

**Comment by chemzqm** [comment]
VSCode create `.vscode` folder with settings in your project, coc.nvim need to create `.vim` folder with settings to resolve this problem.

**Comment by ntcong** [comment]
can we use .env file for some basic settings? Creating a .vim folder seems a bit overkill (no plugin is using it)

**Comment by modesitt-sesco** [comment]
is there any plan on fixing this - how else can I currently use the python interpreter inside `/.venv` in whatever project I happen to be working in?

**Comment by chemzqm** [comment]
> is there any plan on fixing this 

Sure, will fix this ASAP.

**Comment by ntcong** [comment]
1 way to partially fix this is always prefers the current python environment. If vim was started inside a virtualenv then default the interpreter to virtualenv, if it was not then using the default python.

Remembering the choice is great but it might require some hard decision

**Comment by CanyonTurtle** [comment]
I am having the same issue as @ntcong when I try to select a different python interpreter with the quickpick menu. The interpreter doesn't seem to change from its initial value no matter what I choose. I am using:

1. coc-python v1.1.4
3. pipenv 2018.11.26
4. python 3.7.3 (built from source)

Additionally, here is the output of `:CocInfo` on my `nvim` instance.
```
  2 ## versions
  3
  4 vim version: NVIM v0.4.0-566-gd5fd0732e
  5 node version: v10.15.2
  6 coc.nvim version: 0.0.64
  7 term: screen-256color
  8 platform: linux
  9
 10 ## Error messages
 11
 12 ## Output channel: snippets
 13
 14 ## Output channel: PythonStarting Jedi Python language engine.
 15 ##########Linting Output - pylint##########
 16 ##########Linting Output - pylint##########
 17 ************* Module linreg
 18 24,0,error,syntax-error:Format strings are only supported in Python 3.6 and greater (<unknown>, line 24)
 19
 20
```

I am setting up a virtual environment with `pipenv` (i.e. `pipenv shell`) and then starting `nvim` within that environment, and I am sure that the python path of this virtual environment is the very first thing on my path at the time I run nvim. (My path starts like this: `/home/CanyonTurtle/.local/share/virtualenvs/pythontests-jqiNevtW/bin:/…` Yet, it still selects /usr/bin/python3, and I cannot successfully select anything else. `/usr/bin` is also on my path.

@chemzqm thank you for working on this issue. I am glad I found coc-python!

**Comment by modesitt-sesco** [comment]
I agree @ntcong that seems to be the most straightforward. If personal settings need be saved in a `.vim` file and can not be saved elsewhere like to the coc-extensions file in `~/.vim`, and that this is a larger endeavor, I think these choices should be temporarily removed from `:CocCommand` until they work as described.

**Comment by chemzqm** [comment]
Still buggy, need some rework, the logic of this part form vscode-python is quite complex.

**Comment by chemzqm** [comment]
Fixed by use a json file (`~/.config/coc/memos.json`) to store the selected python path.

The limitation is it can't support multiple workspaceFolders.
