### ISSUE TITLE
[Question] What's the difference between using mpls or jedi?

### ISSUE THREAD

**Issue by josefson** [neoclide/coc-python#202]
What is the difference between using mpls or jedi.
Is it just the diagnostics run initally on mpls or are there more features one can do the other can't?

**Comment by chemzqm** [comment]
When using jedi it could use pylint and others for diagnostics, they're totally different for python support

**Comment by himat** [comment]
Which one is better? I have no idea what the real differences between the two are.

**Comment by chemzqm** [comment]
Try coc-pyright if you're writing python3

**Comment by chemzqm** [comment]
Try coc-pyright if you're writing python3
