### ISSUE TITLE
Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by F4zii** [neoclide/coc-python#203]
### Issue

When I open a python file and start using the auto-completion, this error pops up:
`Cannot call write after a stream was destroyed`
<img src="https://cdn.discordapp.com/attachments/648964758128558103/709017501379461150/unknown.png">
I'm using CoC with

### Steps to reproduce
* open a python file with Coc and coc-python extension

**Comment by chemzqm** [comment]
Use :messages
