### ISSUE TITLE
Function parameter window only stays for a while in vim

### ISSUE THREAD

**Issue by wrvsrx** [neoclide/coc-python#205]
## CocInfo

vim version: VIM - Vi IMproved 8.2 8020717
node version: v14.2.0
coc.nvim version: 0.0.78-4f0a63a5d5
term: dumb
platform: linux

## Description

Function parameter window only stays for a while in vim while it works normally in neovim.

- vim
![image](https://user-images.githubusercontent.com/42770726/81567748-56ae5380-93cf-11ea-8e92-758b3ce03110.png)
- nvim
![image](https://user-images.githubusercontent.com/42770726/81567612-1ea71080-93cf-11ea-9ab9-37f393ebd45f.png)

## Reproduce

1. Open a .py file with vim
2. type "range("
3. The function parameter window shows and disappear immediately. Sometime it works well at first, but the problem will appear after you delete the line and type "range(" again.

**Comment by chemzqm** [comment]
Try minimal vimrc

**Comment by wrvsrx** [comment]
I try it with a minimal vimrc and the problem persists. It seems related to the updatetime: in vim the function parameter window only exists for <updatetime> while in neovim it works well.

**Comment by wrvsrx** [comment]
I think it might be related to vim version. In gvim on windows 10 and terminal vim on arch linux, the problem exists while in terminal vim on windows 10, the problem disappears.

**Comment by fcying** [comment]
got the same problem
vim version:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  6 2020 21:16:31)
Included patches: 1-700
Compiled by Homebrew

os: debian10

**Comment by chemzqm** [comment]
Should be bug of vim, can't reproduce on my mac
