### ISSUE TITLE
on nvim it still need jedi with "python.jediEnabled": false

### ISSUE THREAD

**Issue by fcying** [neoclide/coc-python#206]
I set `"python.jediEnabled": false` in my coc-settings.json

on vim, it work fine. 

on nvim, it jump a error
```
[coc.nvim] Jedi error: Traceback (most recent call last):
[coc.nvim] Jedi error:     import jedi
```

**Comment by fcying** [comment]
my fault, on nvim, `coc-settings.json` is on `.config/nvim`

**Comment by dsupru** [comment]
Wanted to add: if `coc-settings.json` is not in `.config/nvim`, create this file and add `{ "python.jediEnabled": false }`.
