### ISSUE TITLE
E0401 errors are not mitigated with the "python.autoComplete.extraPaths" configuration option

### ISSUE THREAD

**Issue by rmo20** [neoclide/coc-python#208]
Consider a directory with the following structure
```
$ tree $(pwd)
/home/beep1560/mytest
├── main.py
└── my_dir
    └── my_module.py

1 directory, 2 files
```
whose files have the following content
```
$ cat main.py
from my_module import foo
foo()
```
```
$ cat my_dir/my_module.py
def foo():
    print("foo")
```
Now, consider the following `~/.vim/coc-settings.json`
```
{
	"python.autoComplete.extraPaths": [ "/home/beep1560/mytest/my_dir" ]
}
```
Opening `main.py` shows the following error (see image below)

![image](https://user-images.githubusercontent.com/57326298/81939094-815cff80-95bb-11ea-9e38-7547db900ba3.png)

Isn't it supposed that the `python.autoComplete.extraPaths` configuration option is used to avoid the `import` error (which is shown in the image)?

**Comment by chemzqm** [comment]
It's used for completion only, you have to configure your linter as well.
