### ISSUE TITLE
Code completion for `matplotlib` objects.

### ISSUE THREAD

**Issue by whereistejas** [neoclide/coc-python#215]
Hey! First of all I want to thank all the contributors for an awesome vim plugin.

Most of my work revolves around the `matplotlib` library.

However, I am having trouble getting code-completion to work for objects of that library. For example,
```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.plot([some-random-numpy-array])
```

I'm not getting code-completion suggestions for the methods of the `ax` and `fig` objects.
Is this a known issue?

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by whereistejas** [comment]
@chemzqm I tried debugging it. It won't show any useful output.

**Comment by chemzqm** [comment]
It won't show output if you're using jedit.

**Comment by chemzqm** [comment]
We can't do anything since it should be problem of jedi.

**Comment by whereistejas** [comment]
Thanks :)
