### ISSUE TITLE
Formatting problems

### ISSUE THREAD

**Issue by Rikorose** [neoclide/coc-python#22]
Hi,

I am not able to use formatting (with black) with this extension. I'm getting `Error on 'format': undefined` errors when using `:call CocAction('format')` or `:call CocAction('format', @%)`.

Can you provide documentation how to format the whole buffer using this extension?

Thanks

**Comment by LarsMichelsen** [comment]
Same issue over here. Is there a way I can assist to track this down?

**Comment by chemzqm** [comment]
Debug the code in chrome https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim, I will fix it.

**Comment by LarsMichelsen** [comment]
Works now! :1st_place_medal:
