### ISSUE TITLE
[coc.nvim] error: Some plugin change completeopt on insert mode: Last set from ~/.config/nvim/plugged/jedi-vim/autoload/jedi.vim line 716!

### ISSUE THREAD

**Issue by lyukrys** [neoclide/coc-python#220]
I installed coc and the extension coc-python, i installed jedi using pip. When I attempt to use autocomplete I get this error

[coc.nvim] error: Some plugin change completeopt on insert mode: Last set from ~/.config/nvim/plugged/jedi-vim/autoload/jedi.vim line 716!

**Comment by chemzqm** [comment]
Use one of them

**Comment by chemzqm** [comment]
Use one of them

**Comment by danilofreire** [comment]
@lyukrys you need to use either coc-python or jedi to autocomplete your code. I had the same issue and I solved it by adding the following line to my `.vimrc`: `let g:jedi#completions_enabled = 0`. It will disable jedi's autocompletion features. It has worked for me, although I'm not an expert in vim. I hope it works for you too! :)
