### ISSUE TITLE
Doesn't work with virtualenv

### ISSUE THREAD

**Issue by ichirou2910** [neoclide/coc-python#233]
Hi, I work on multiple Python projects and I don't want to install all neccessary packages globally. The problem is coc-python only detects globally installed packages and suggests/diagnose based on them but not ones installed in virtualenv, which annoys me quite a bit. Is there any way to config coc-python to work with the virtualenv I am working on? Thanks for reading.
Sample image:
![image](https://user-images.githubusercontent.com/51302893/84844097-e51f9000-b073-11ea-8894-bfe63a4c4060.png)

**Comment by rbhanot4739** [comment]
You can specify the pythonPath per workspace and then it will work as expected.

**Comment by ichirou2910** [comment]
Thanks. It worked well ^^
One more question though. Is it possible to automatically create a local coc-settings.json when I create a new virtualenv with pythonPath set to python of that virtualenv?

**Comment by ichirou2910** [comment]
Hi, after playing around a bit I found the solution (for anyone using virtualenvwrapper like me)
Put these lines at the end of function mkvirtualenv in ~/.local/bin/virtualenvwrapper.sh or /usr/local/bin/virtualenvwrapper
```
    PROJ_PATH="`dirname \"$0\"`"              # relative
    PROJ_PATH="`( cd \"$PROJ_PATH\" && pwd )`"  # absolutized and normalized
    
    echo "$PROJ_PATH/$1"

    mkdir -p $PROJ_PATH/$1/.vim

    cat >> $PROJ_PATH/$1/.vim/coc-settings.json <<- EOF
    {
        "python.pythonPath": "~/.virtualenvs/$1/bin/python"
    }
EOF
```
Remember to source virtualenvwrapper.sh again. After that, executing mkvirtualenv will generate the coc-settings.json file with pythonPath set accordingly
