### ISSUE TITLE
autocomplete with underscore doesn't work

### ISSUE THREAD

**Issue by matteha** [neoclide/coc-python#27]
It seems that using the _ character renders autocomplete options invalid. For instance, see below (using MPLS, might be on jedi too).

These are the options:

<img width="286" alt="Screen Shot 2019-04-02 at 12 26 29 PM" src="https://user-images.githubusercontent.com/36545991/55419498-dd450000-5542-11e9-9341-c0d0d49cd67f.png">

Now with the _ it doesnt show the options anymore:

<img width="398" alt="Screen Shot 2019-04-02 at 12 26 56 PM" src="https://user-images.githubusercontent.com/36545991/55419532-f2219380-5542-11e9-8fd8-be574ddb4370.png">

Is there a reason for this / can this be fixed? Would be great!

Skipping the _ does show the options, some of them, through fuzzy matching:

<img width="291" alt="Screen Shot 2019-04-02 at 12 26 49 PM" src="https://user-images.githubusercontent.com/36545991/55419549-ff3e8280-5542-11e9-9a40-b8147e847481.png">

**Comment by chemzqm** [comment]
Looks like you don't have `_` in your `&iskeyword`. Check out `:echo &iskeyword`

**Comment by chemzqm** [comment]
Fix on master of coc.nvim, it does filter even if it's not iskeyword.
