### ISSUE TITLE
suid privilege escalation 

### ISSUE THREAD

**Issue by abdellatif-dev** [neoclide/coc-python#274]
Changes file file permissions from / to read only
As I understand it done via suid privilege escalation that broke my systemand make my machine stuck at initramfs Until I fix using feck command i don't get why you need a sudo-prompt in a vim plugin

**Comment by FedericoAntoniazzi** [comment]
Probably you've run pip as root and then broken the system completely by installing something else using sudo...

**Comment by FedericoAntoniazzi** [comment]
This plugin doesn't need root access to work so it's your fault.
I highly recommend you to close this issue
