### ISSUE TITLE
Place cursor inside brackets when python.autoComplete.addBrackets is true.

### ISSUE THREAD

**Issue by karambaq** [neoclide/coc-python#31]
With enabled python.autoComplete.addBrackets while autocompleting cursor places after brackets even if function requires arguments.

**Comment by chemzqm** [comment]
It's bug of coc.nvim happens when you have nested snippet session, fixed on master of coc.nvim.

Use `:call coc#util#install()` to update.

**Comment by esn89** [comment]
I have a problem a little bit related to this:

despite enabling this in my :CocConfig, when I select the autocomplete function, I do not see the brackets completing.  

I use <TAB> to select the function that I want, then hit <ENTER> but I do not see an opening bracket of (
