### ISSUE TITLE
Can't get out of the terminal one interacted with

### ISSUE THREAD

**Issue by shy00n** [neoclide/coc-python#316]
I moved into the terminal window with the usual `<c-w>w`, but now I can get out of there after hitting **`i` or `a`**.  (If I do not edit, then I can get out with '<c-w>w'.
Seems like the bash terminal has taken over & refuses to take the usual `<c-w>w`  or `<c-w><c-w.>` .  `<esc>` or `:` does not work. The only solution is to kill the terminal.
There should b an easy answer, but I lose.
NVIM v0.4.3
$ uname -a
Linux DESKTOP-3D 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
All coc-python & everything is new, as I just PlugUpdate & UpdateRemotePlugins.
Thanks,

**Comment by yelled1** [comment]
This does the job
tnoremap <Esc> <C-\><C-n><C-w><C-w>

**Comment by shy00n** [comment]
This does the job
tnoremap <Esc> <C-\><C-n><C-w><C-w>
more fuller would be [here](https://vi.stackexchange.com/questions/4919/exit-from-terminal-mode-in-neovim-vim-8)
