### ISSUE TITLE
Debug [coc.nvim] source jedi timeout after 5000ms

### ISSUE THREAD

**Issue by zhou13** [neoclide/coc-python#33]
When input `im` in a `*.py`, I get `[coc.nvim] source jedi timeout after 5000ms`.  I cannot get any completion from `JD` (jedi).  MPLS also times out for me. I am not sure what happens.  The same configuration file works on another machine.  Below is my `coc-settings.json`:
 ```{
    "suggest.timeout":  5000,
    "diagnostic.checkCurrentLine": true,
    "emmet.includeLanguages": {"markdown": "html"},
    "emmet.excludeLanguages": [],
    "python.jediEnabled": true,
    "list.normalMappings": {
        "<C-c>": "do:exit"
    },
    "list.insertMappings": {
        "<C-c>": "do:exit"
    },
    "languageserver": {
        "ccls": {
            "command": "ccls",
            "filetypes": ["c", "cpp", "objc", "objcpp"],
            "rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],
            "initializationOptions": {
                "cache": {
                    "directory": "/tmp/ccls"
                }
            }
        }
    }
}
```

**Comment by chemzqm** [comment]
It looks like problem of jedi version.
Checkout log of coc.nvim to get the error https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

**Comment by randrej** [comment]
Please write your results here, I'm having trouble with some Jedi versions, too, especially when working on projects involving PyQt5.

**Comment by zhou13** [comment]
After upgrading the package, the error disappears. But I still cannot get the completion in python.  I check the log and I think the key part is
```
2019-04-25T13:42:02.988 ERROR (pid:5929) [extension-coc-python] - Python Extension: stderr jediProxy, Error (stderr) Traceback (most recent call last):
  File "completion.py", line 647, in <module>

2019-04-25T13:42:02.988 ERROR (pid:5929) [extension-coc-python] - Python Extension: stderr jediProxy, Error (stderr)     import jedi
ModuleNotFoundError: No module named 'jedi'
```

The full log is at https://bpaste.net/show/897e03d8fe53. 

I can successfully execute `import jedi` in system python and vim's `python3 import jedi`.

**Comment by zhou13** [comment]
Now I can get completion from jedi by putting `    "python.pythonPath": "python3",` in my coc-setting.  Not sure why because I am on archlinux the default python is already python3. Is `coc.nvim` do something special with conda or python's path?

**Comment by chemzqm** [comment]
You can use `"python.jediPath"` to specify folder of jedi module.

**Comment by zhou13** [comment]
What is the default `jediPath`?

**Comment by chemzqm** [comment]
It's resolved from packages of your current selected python intepreter, checkout `coc-status` for status line integration.

**Comment by zhou13** [comment]
I add coc-status to my airline.  It is not documented yet:
```
call airline#parts#define_function('coc_status', 'coc#status')
let g:airline_section_y = airline#section#create_right(['coc_status','ffenc'])
```
But that seems does not help this. I still do not understand why `"python.pythonPath": "python3"` works for me while `"python.pythonPath": "python"` yields `No module named jedi`.  On my computer, I have
```
$ ls -al `which python3`
lrwxrwxrwx 1 root root 9 Mar 26 14:43 /usr/bin/python3 -> python3.7
$ ls -al `which python`
lrwxrwxrwx 1 root root 7 Mar 26 14:43 /usr/bin/python -> python3
```

**Comment by chemzqm** [comment]
@zhou13 Because they're different python and they have different site packages.

**Comment by zhou13** [comment]
But you can see that `/usr/bin/python3` really links to `/usr/bin/python`...

**Comment by zhou13** [comment]
![tty](https://user-images.githubusercontent.com/576382/56775060-36870480-677a-11e9-92c7-cd26b12bfd61.gif)

**Comment by zhou13** [comment]
You can see that `jedi` imports correctly in `python` but it does not work in coc-python.

**Comment by chemzqm** [comment]
Run `:CocCommand python.setInterpreter` to get current python, it would be not your current `python` in $PATH.

**Comment by zhou13** [comment]
It is `/home/zyc/.miniconda3/envs/lcnn/bin/python`.  Not sure why. Is that because I install `coc-python` when I was in that miniconda's virtualenv and for some reaso `coc-python` hardcodes it?

**Comment by zhou13** [comment]
@randrej, your problem is probably due to davidhalter/jedi#1236.

**Comment by chemzqm** [comment]
There's memos that remembers your global choice, you can clean it by `rm ~/.config/coc/memos.json` in your shell.

**Comment by zhou13** [comment]
That explains the problem. It seems that `coc-python` will always remember the python when it first initializes. After I delete `~/.config/coc/memos.json`, it hardcodes `/usr/bin/python`.  So if I am inside some virtualenv, it still uses `/usr/bin/python` by default.  This is confusing and not straight forward.  Is it possible to change the behavior so that it would automatically choose the python based on current `$PATH`?

**Comment by chemzqm** [comment]
> Is it possible to change the behavior so that it would automatically choose the python based on current $PATH?

It was fixed, checkout version of your coc-python.

**Comment by zhou13** [comment]
`:CocList extensions` told me that I am at `coc-python 1.1.6`.  Is that the newest version of `coc-python`?

**Comment by chemzqm** [comment]
It should use python from your current $PATH unless you have `"python.pythonPath"` changed or you used `:CocCommand python.setInterpreter` to configure python interpreter for current workspace folder.

Could be issue of wrong workspaceFolder, checkout https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders.

I can't reproduce your problem, you can checkout the log of coc.nvim https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim.

**Comment by chemzqm** [comment]
It only select python interpreter when python inside your workspaceFolder, so if your python outside current workspaceFolder, you have to select the interpreter once for current workspaceFolder.

**Comment by randrej** [comment]
> @randrej, your problem is probably due to [davidhalter/jedi#1236](https://github.com/davidhalter/jedi/issues/1236).

Yep, you can see that the last post is mine. It is a jedi problem, so I downgraded jedi (and posted PR #37 to allow using jedi 12.1 with coc-python), which solves my issue is solved for now.

**Comment by chemzqm** [comment]
Use `python.jediPath` setting to make sure coc-python load jedi module from that directory.

**Comment by z-huabao** [comment]
> It should use python from your current $PATH unless you have `"python.pythonPath"` changed or you used `:CocCommand python.setInterpreter` to configure python interpreter for current workspace folder.
> 
> Could be issue of wrong workspaceFolder, checkout https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders.
> 
> I can't reproduce your problem, you can checkout the log of coc.nvim https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim.

`:CocCommand python.setInterpreter` solve it

**Comment by krisezra87** [comment]
I see this is old and I stumbled here before as a new python programmer, but I will mention that another reason you can get this error is if jedi is not installed at all.  You will need to pip install jedi (or alternate) if nothing else in here is useful.

Yes it's a noob problem, but sometimes you need the noob answer!
