### ISSUE TITLE
[solved] can not make coc-python auto-completion work with Jedi

### ISSUE THREAD

**Issue by jdhao** [neoclide/coc-python#40]
Update: it seems that the problem is due to that Jedi package is not in the latest version, although I don not understand why.

## problem description
I tried to install coc.nvim and coc-python extension on two machines: Mac and Linux. On Mac, it works as expected after install. But on Linux, I can not make the completion work.

## My environment

+ Mac: mac os mojave
+ Linux: CentOS 7.4
+ Neovim: 0.4.0
+ Python: Python 3.5+ (bundled with Anaconda)
+ Jedi

## steps I have tried

Here is what I do

1. Install Nodejs (I have installed a binary version of nodejs since I do not have root rights) and set its path correctly.
2. Install yarn via the script provided in the coc.nvim readme. I can call `yarn` on the command line

3.  Install coc.nvim via vim-plug

4. Install coc-python via the command `:CocInstall coc-python`. (It seems that coc-python supports both Jedi and MPLS and Jedi is used by default. I have already installed Jedi.)

**On my Mac, this is all I do to make the auto-completion work for Python file.** 
But on Linux, it does not work.

## Steps further tried on Linux

I run the `:checkhealth` command inside neovim and found some error related to coc.nvim and nodejs. For coc.nvim, it shows that `:pyx`  does not work. All it prompted me to use `:call coc#util#build()` command.  For nodejs, the warning is that `neovim` is not installed.

I add `set pyxversion=3` to my config and run the command `:call coc#util#build()`  and the build is successful.

I also installed neovim module via

```
yarn global add neovim
```

After all these steps, `:checkhealth` shows no errors or warnings related to coc.nvim

```
health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Build javascript found
  - OK: Service started

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - WARNING: No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
    - ADVICE:
      - :help clipboard

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /bin/python2 does not have the "neovim" module. :help provider-python
          /bin/python2.7 does not have the "neovim" module. :help provider-python
          python2.6 not found in search path or not executable.
          /home/haojiedong/tools/anaconda3/bin/python is Python 3.6 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /home/haojiedong/tools/anaconda3/bin/python3
  - INFO: Python version: 3.6.5
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v10.15.3
  - INFO: Neovim node.js host: /home/haojiedong/.config/yarn/global//node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.5.0
```

After that, I open a python file and auto-completion still does not work for packages and modules. Any idea, what should I try next?

## what works

It should be noted that completion for words inside the buffer works:

![image](https://user-images.githubusercontent.com/16662357/57424401-1e1eeb80-724a-11e9-9def-3f97a37eee31.png)

But auto-completion for packages does not work:

![image](https://user-images.githubusercontent.com/16662357/57424440-41e23180-724a-11e9-9d72-680637c15c15.png)

I also tried to see if auto-completion for viml works by installing the following plugin:

```
Plug 'Shougo/neco-vim'
Plug 'neoclide/coc-neco'
```

Auto-completion does work for vim script as shown below

![image](https://user-images.githubusercontent.com/16662357/57424562-a7ceb900-724a-11e9-95fa-1b7a532b431a.png)

So it seems that coc.nvim works. The issue may be in coc-python.  Currently, I only add the following config to my `coc-settings.json` file:

```
{
"suggest.timeout": 5000
}
```
( On my Mac, I can use python auto-completion without setting anything inside this file. )

I have also tried to remove coc.nvim and re-install from scratch. But it does not solve the problem either.

## My minimal non-working config

Here is my minimal non-working config:

```
call plug#begin(expand('~/.local/share/nvim/plugged'))
Plug 'neoclide/coc.nvim', {'do': './install.sh'}
Plug 'Shougo/neco-vim'
Plug 'neoclide/coc-neco'
call plug#end()

set pyxversion=3
```

## Follow up

After all these step, I tried to update jedi:

```
conda update jedi
```

Now the auto-completion finally works! Maybe it is caused by Jedi? But if I use deoplete and deoplete-jedi for auto-completion, there is no such issue.

I not sure why updating to latest Jedi solves this issue. Does coc-python depends on some specific features from the latest version of Jedi?  Maybe there should be a warning message about the Jedi is not in the latest version when using `:checkhealth`.

**Comment by soywod** [comment]
I got the same problem here, I needed to uninstall and reinstall manually `jedi` via `pip install --user jedi`.

**Comment by decko** [comment]
Same here too. Needed to install jedi on my current virtualenv to make discovery and autocomplete works.

**Comment by tpict** [comment]
Is there a minimum version requirement for Jedi? I wasn't getting completions on 0.11.1, but 0.13.3 is working

**Comment by yangkev** [comment]
Just to be clear, does `coc-python` *NOT* automatically install `jedi` like it does MSPL when `python.jediEnabled": false`?

And therefore the user must manually install `jedi` for their python environment?

**Comment by chemzqm** [comment]
Yes, it doesn't help for install jedi, same as vscode-python.

**Comment by surasshu0x0** [comment]
> Yes, it doesn't help for install jedi, same as vscode-python.
> 
> Use `python.jediPath` to avoid install jedi for different project.

if anyone has a problem with this,

- install jedi globally -`pip3 install jedi`
- use pip3 to find jedi path `pip3 show jedi`
- go to your coc-settings.json add the path shown by pip3 (exactly that path) and use it as the value of `python.jediPath` 

_Note_ : I used pip3 to target python3 because i have python2 installed also,  `pip` can also be used depending on your python installations
