### ISSUE TITLE
Error on :Gwrite

### ISSUE THREAD

**Issue by hovnatan** [neoclide/coc-python#45]
When I save file using `vim-fugitive`'s  `:Gwrite` I get the following error in `coc-python`: 
![2019-05-26-115743_1919x145_scrot](https://user-images.githubusercontent.com/8426582/58379030-8857c000-7fae-11e9-9e4c-8c5814dd7b87.png). 

You can see my config at https://github.com/hovnatan/dotfiles/tree/master/.config/nvim

**Comment by chemzqm** [comment]
Should be fixed now.
