### ISSUE TITLE
Selecting flake8 each time and Python2

### ISSUE THREAD

**Issue by adam0z** [neoclide/coc-python#47]
I have no pylint installed - just flake8.
Each time I open .py file I get a question:
```
Linter pylint is not installed.:
1. Install
2. Select linter
3. Do not show again
```
I select 2. and then I check flake8.
It looks like it never works and the choice is not saved.
I added in my `~/.config/nvim/coc-settings.json`:
```
{
  "python.setInterpreter": "python2",
  "python.setLinter": "flake8"
}
```
And still it does not help. Python version is also choosen inproper (Python3 instead of Python2)

And moreover, how to always show the linter results?

**Comment by chemzqm** [comment]
`"python.setInterpreter"` and `"python.setLinter"` are not valid configuration, please read Readme and install coc-json.

**Comment by chemzqm** [comment]
What do you mean by  `always show the linter results`?

**Comment by adam0z** [comment]
Thanks. Flake8 works with my settings:
```
{
        "python.jediEnabled": true,
        "python.linting.pylintEnabled": false,
        "python.linting.flake8Enabled": true
}
```
How to change python interpreter version to Python2?

I see red ">>" on linting PEP8 errors. How to show the error message?
There is no message if a cursor in at the bad line.

**Comment by chemzqm** [comment]
> How to change python interpreter version to Python2?

Use command `:CocCommand python.setInterpreter`

> There is no message if a cursor in at the bad line.

It's checked by error range, use `"diagnostic.checkCurrentLine": true` to check current line.

**Comment by jsatk** [comment]
@chemzqm I took am having a similar issue. Every time I load a python file it asks me to install pylint. I tell it to use flake8 instead. It always asks me a second time. I select flake 8 again and it's done. If I close vim and re-open file the same thing happens. 

When I run `:CocCommand python.setInterpreter` it's pointed at the correct virtualenv version of Python 2.

**Comment by jsatk** [comment]
Here's a screenshot of what I see in Vim 8. 
<img width="1920" alt="Screen Shot 2019-06-07 at 6 52 44 PM" src="https://user-images.githubusercontent.com/1005550/59140669-a978c300-8955-11e9-887e-44cb54077bd2.png">

**Comment by jsatk** [comment]
@chemzqm can we re-open this?

**Comment by jsatk** [comment]
This is still a big issue :(

**Comment by chemzqm** [comment]
Can't reproduce your problem.
Try upgrade your coc.nvim, or create a `.vim/coc-settings.json` in your project root.

**Comment by jsatk** [comment]
I am on the latest. I actually just set up a brand new computer today and re-ran into this issue which made me revisit this thread. I finally pressed `3` to ignore it (like I did before). But seems less than ideal.
