### ISSUE TITLE
'Error output from python: Unable to find document' for files without extension

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc-python#5]
Getting `[coc.nvim] Error output from python: Unable to find document file:///home/me/foo` for python files with shebang but without extension (`foo` file causes error, `foo.py` doesn't).

**Comment by chemzqm** [comment]
The problem is when you edit file in home directory, the workspaceFolder of coc is undefined.

**Comment by oblitum** [comment]
Sorry the confusion, my cwd was not home actually, it was `/home/me/something/`.

**Comment by oblitum** [comment]
The same file was causing error just by renaming and removing extension.

**Comment by chemzqm** [comment]
I've changed coc-python use jedi by default, duplicate of #10.
