### ISSUE TITLE
python.autoComplete.addBrackets not adding brackets

### ISSUE THREAD

**Issue by esn89** [neoclide/coc-python#50]
I have set that value to true:
https://pastebin.com/nvUap7CL

Now when I type into vim with:
`object.` a list of suggested functions show up and I select it by hitting \<ENTER\>, however, I do not see the autocompleted braces with the cursor in the middle.

I expect:
```
object.function(|)
```

**Comment by chemzqm** [comment]
`python.autoComplete.addBrackets ` only works with jedi, but you have disabled jedi.

**Comment by esn89** [comment]
With this being closed since it depends on Jedi, I was wondering if it was possible to get this incorporated:

https://github.com/microsoft/python-language-server/issues/868

On the languageserver option side, I see that this is implemented.  That way, for those who do not choose to use Jedi, the could also get bracket completion.

**Comment by chemzqm** [comment]
I think you have to use beta version of mpls and find out the way to pass that option.

**Comment by esn89** [comment]
Ah, okay.  Thank you.  I will try that.
