### ISSUE TITLE
Repeatedly being asked "Use MPLS instead of jedi?"

### ISSUE THREAD

**Issue by mike-hearn** [neoclide/coc-python#57]
When I edit python files, I get repeatedly asked whether I want to use MPLS or Jedi, and choosing Y or N doesn't seem to make a difference either way. It seems to be triggered by when the autocomplete attempts to return results, e.g. after a period or when `coc#refresh()` is manually called.

This is the experience editing a new Django app with a fresh virtualenv with only Django installed. See the bottom of the screenshot for the repeated `Use MPLS instead of jedi? [Y]es, (N)o` prompts:

![cocpython](https://user-images.githubusercontent.com/1016999/60838324-6b5f0100-a198-11e9-80dc-8c0b86e1cf4b.gif)

Here is my [init.vim](https://github.com/mike-hearn/dotfiles/blob/master/nvim/.config/nvim/init.vim) and here is my [coc-settings.json](https://github.com/mike-hearn/dotfiles/blob/master/nvim/.config/nvim/coc-settings.json).

This is on Fedora 29 and Neovim 0.3.3.

**Comment by mike-hearn** [comment]
Thanks for the quick fix. But it looks like 7afa320 fixed the repetitive prompts when choosing `N`, selecting `Y` (which sets `"python.jediEnabled": false` locally) is still causing repeated prompts.

![cocpython-again](https://user-images.githubusercontent.com/1016999/60908763-a7529e80-a24a-11e9-8c4a-4df881080c0e.gif)

**Comment by chemzqm** [comment]
You need to wait MPLS installed, checkout `:h coc-status` for statusline integration.

**Comment by mike-hearn** [comment]
Thanks for the direction, I installed the statusline integration (which is awesome) but I still have questions.

What should I be seeing in the status line / how long does MPLS take to install? Even leaving neovim open for several minutes still results in the repeated prompts.

![cocpython-v3](https://user-images.githubusercontent.com/1016999/60909308-f220e600-a24b-11e9-82bb-0e718a9f71ff.gif)

**Comment by chemzqm** [comment]
No idea, it should only be shown when you have `"jedi.enabled": true`

**Comment by mike-hearn** [comment]
Hmm. The only line in my .vim/coc-settings is:

```
{
  "python.jediEnabled": false
}
```

and I've completely removed the `python.jediEnabled` config entry from my global `coc-settings.json`, so it's not set to `true` anywhere.

I'd love to force it to use MPLS, but I can't seem to get around the repeated prompts, and I can't seem to get it to install MPLS. It's not the end of the world if I have to keep using jedi w/ coc.

**Comment by mike-hearn** [comment]
Struggling to create a Docker container, but I just wanted to add one more piece of info, which is that `:CocInfo` seems to suggest that the MPLS is running successfully, and the fact that the autocomplete is returning things tagged `[LS]` (as opposed to `[JD]`) seems to also indicate it's working correctly. The only problem is the repeated prompt, which I cannot get rid of for the life of me.

One more screencast showing `:CocInfo` and my settings files.

![cocpython-v4](https://user-images.githubusercontent.com/1016999/60912534-89d60280-a253-11e9-8017-a49497392245.gif)

**Comment by stsewd** [comment]
@mike-hearn thanks, I was struggling with this the whole week. Just for reference, the coc config directory is in `~/.config/coc`

**Comment by reisnobre** [comment]
Having the same problem... Trying to blowing away my config...

**Comment by eyemyth** [comment]
I tracked this down on my system to ~/.config/coc/memos.json

It had a strange line near the end of the first object: `}913e8a83cb41c15e466ef809d41"`

I just deleted memos.json.

**Comment by loxosceles** [comment]
Deleting memos.json doesn't work for me. It keeps asking me on almost every key stroke.

**Comment by alesveselka** [comment]
Deleting `memos.json` does work for me, but I have to do it every day, as it always re-appear. It seems though that the content of the `memos.json` is malformed and `coc` probably fails to read it?

**Comment by AndreaHasani** [comment]
Any actual fix for this. Its driving me insane. On every new file I create it keeps asking me a few times and its annoying.

**Comment by jpfender** [comment]
I'm also having this issue, it's extremely annoying.

The only content in my CocConfig is

```
{
    "python.jediEnabled": false
}
```
But it keeps asking me every few keystrokes.

**Comment by loxosceles** [comment]
I think this issue should be reopend. Deleting memos.json doesn't work as a permanent fix.
