### ISSUE TITLE
Pylint seems to ignore the rcfile

### ISSUE THREAD

**Issue by MadWombat** [neoclide/coc-python#59]
When I run pylint from command line, it works as expected. But when I get the linter output in nvim, I get a bunch of import errors because the django plugin specified in the config file doesn't get loaded. Is there anything special I need to do to make pylint use the ~/.pylintrc?

**Comment by chemzqm** [comment]
> the django plugin specified in the config file doesn't get loaded

It's should be caused by the plugin can't be found by the python interpreter you have selected to work with your current project.

**Comment by MadWombat** [comment]
II seem to have created two issues for the same problem. The other issue is #62. I think this one is safe to close.
