### ISSUE TITLE
Formatter error

### ISSUE THREAD

**Issue by UzimakiNaruto** [neoclide/coc-python#65]
I was already uninstall the black formatter and set the option  "python.formatting.provider" to "yapf",  But I still get the error message: 
> [coc.nvim] Black does not support the "Format Selection" command.   

Same error with set to "autopep8" or nothing to "python.formatting.provider"

**Comment by UzimakiNaruto** [comment]
When I debug the coc.nvim by chrome. I found the value of option 'python.formatting.provider' is 'black', 
 ![hh](http://ww1.sinaimg.cn/large/9426256bly1g5a5k01cxdj21wc17wwyy.jpg)

But I was set to yapf via 
  > "python.formatting.provider": "yapf",

**Comment by chemzqm** [comment]
Could be in `.vim/coc-settings.json` in your project root.

**Comment by UzimakiNaruto** [comment]
My project root dir is ~/Desktop, and my python file is a single file.

**Comment by chemzqm** [comment]
I've tested, it works as expected for me.

**Comment by UzimakiNaruto** [comment]
![](http://ww1.sinaimg.cn/large/9426256bly1g5feb60uncj224y1b24gr.jpg)

![](http://ww1.sinaimg.cn/large/9426256bly1g5febnz6lej20sg0qugox.jpg)


I debug it again and found all things is right but the python.formatting.provider  😭

**Comment by chemzqm** [comment]
The configuration would be overwritten by vim function `coc#config`, try use minimal vimrc.

**Comment by UzimakiNaruto** [comment]
I debug it again.

![](http://ww1.sinaimg.cn/large/9426256bly1g5non40hoaj22801e0keu.jpg)

![](http://ww1.sinaimg.cn/large/9426256bly1g5noodwattj227q1du4h3.jpg)

And I found **_workspaceConfiguration** was wrong, en~~~,  what's the meaning??  

PS:  My desktop doesn't have the cot-settings.json.
😃

**Comment by UzimakiNaruto** [comment]
Oh, When i step into the function **getFolderConfiguration**, I found have a hide folder .vim, it contains a coc-settings.json ..  I don't konw what happened .  😭 

Thanks for your help!
