### ISSUE TITLE
Is it possible to use different interpreters in different workspaces?

### ISSUE THREAD

**Issue by svermeulen** [neoclide/coc-python#70]
It seems like there is one global interpreter enabled at any one time.  Is this an intentional design choice?  I work in lots of different projects that use different virtual envs so would love it if this could be changed on a per-workspace basis

**Comment by chemzqm** [comment]
Use folder configuration: `.vim/coc-settings.json`: https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file

It has complex logic for python interpreter resolve when it defaults to `python`.
