### ISSUE TITLE
Command python.upgradePythonLanguageServer not found

### ISSUE THREAD

**Issue by wbthomason** [neoclide/coc-python#73]
When I try to run `:CocCommand python.upgradePythonLanguageServer` (using completion for the command name from the menu that comes up when `:CocCommand` is run without arguments, to avoid typos), I get the error in the title. `:CocInfo` reports nothing unusual and my `:CocConfig` for `coc-python` only has `"python.jediEnabled": false` (so it should be using MPLS) and `"python.formatting.provider": "yapf"`. I'm happy to provide more information, but I'm not really sure where to start debugging this.

**Comment by chemzqm** [comment]
You have to open python file before invoke this command

**Comment by wbthomason** [comment]
Ah! Thank you; I did not know that. With other coc plugins (e.g. coc-texlab), the upgrade command has worked outside of buffers of the language server's filetype.

Thanks!

**Comment by Congee** [comment]
@chemzqm opening file does not help. how should I debug it?
