### ISSUE TITLE
[coc.nvim] Command: python.setInterpreter not found

### ISSUE THREAD

**Issue by 5ilvers** [neoclide/coc-python#78]
Hi

I'm having some weird issue with `python.setInterpreter`
when i try to invoke it with CocCommand, i keep getting
`[coc.nvim] Command: python.setInterpreter not found`

but after i try `python.sortImports`, `python.setInterpreter` starts working, now I have to run `python.sortImports` everytime before `python.setInterpreter`

**Comment by chemzqm** [comment]
You need open python file first
