### ISSUE TITLE
Will config be added to the coc-settings.json through CocInstall coc-python?

### ISSUE THREAD

**Issue by jidibinlin** [neoclide/coc-python#82]
I installed the coc-python extension but it didn`t wrote the json config to my coc-settings.json

**Comment by fannheyward** [comment]
No, CocInstall will not add config to coc-settings.json.

**Comment by jidibinlin** [comment]
## so what you mean here.
![2019-08-29_17-49](https://user-images.githubusercontent.com/38578679/63930122-50688900-ca85-11e9-9bbf-46315a2fce4d.png)

**Comment by fannheyward** [comment]
That means, if you installed coc-python, the config list bellow https://github.com/neoclide/coc.nvim/wiki/Language-servers#python is not needed.
