### ISSUE TITLE
Cannot jump to definition

### ISSUE THREAD

**Issue by harry-kim** [neoclide/coc-python#87]
I try to `gd` on a function but i keep getting `[coc.nvim] Definition provider not found for current document`

Also I enabled jedi but I get `Starting Microsoft Python language server.` in my CocInfo

my coc config
```
{
  "python.jediEnabled": true,
  "python.pythonPath": "/Users/hkim/.virtualenvs/my_env/bin/python",
  "python.linting.pylintEnabled": false,
  "python.linting.flake8Enabled": true,
  "python.linting.enabled": true,
  "coc.preferences.jumpCommand": "drop",
  "tsserver.npm": "/usr/local/bin/npm",
  "diagnostic.checkCurrentLine": true,
  "coc.preferences.currentFunctionSymbolAutoUpdate": true
}
```

**Comment by doronbehar** [comment]
Do you have Jedi installed?

**Comment by harry-kim** [comment]
yes

**Comment by eyalk5** [comment]
For me, it happens with jediEnabled=False

**Comment by harry-kim** [comment]
I was able to fix this by changing my version of node

**Comment by Ferdi265** [comment]
@harry-kim: which version of node did you change to?

**Comment by chemzqm** [comment]
Should be jedi not working.
Checkout verbose output https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
