### ISSUE TITLE
TypeError: Cannot read property 'uri' of null

### ISSUE THREAD

**Issue by ghost** [neoclide/coc-python#9]
Hi!

After installing coc-python, i open python file and get a error message like in title of this issue.

![2019-03-27-121333_1680x1050_scrot](https://user-images.githubusercontent.com/48855491/55071856-fb65b880-5089-11e9-812d-9da22665d655.png)

**Comment by chemzqm** [comment]
You need to create file before open it, this is how VSCode works, but not vim.

**Comment by chemzqm** [comment]
Duplicate of #6 .
