### ISSUE TITLE
Syntax highlighting inside fstrings.

### ISSUE THREAD

**Issue by scarlehoff** [neoclide/coc-python#91]
I think an extremely nice feature to have would be syntax highlighting for the code inside fstrings such as

```
s = f"The sum of {six} and {four} is {six + four}"
```

right now all of that is of the same color and it makes me suffer.

Note: not sure whether this ought to be here or rather in https://github.com/neoclide/coc-highlight or whether you guys don't deal with highlighting at all. Just changed most of my vim stuff for coc and was wondering whether this could be also provided.

**Comment by chemzqm** [comment]
It's not lsp feature, use other plugin for it

**Comment by Congee** [comment]
FWIW, the upstream is eyeing on this https://github.com/microsoft/python-language-server/issues/1903
