### ISSUE TITLE
Lint only works when saving files (using jedi)

### ISSUE THREAD

**Issue by qifei9** [neoclide/coc-python#94]
Problem: 

the lint info never change when I type, it only updates when every time I save  the file with `:w`. Both pylint and flake8 were tested, and even when I use a minimal `init.vim` and `coc-settings.json` and uninstall all the other plugins, the problem always remains.

Update:

It seems `coc-json` works fine for json files. Lint updates without saving file.

init.vim:
``` vim
call plug#begin('~/.local/share/nvim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()


let g:coc_global_extensions = ['coc-python']
```

CocConfig:
``` json
{
    "python.jediEnabled": true
}
```

neovim v0.4.2
python 3.7.4

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-python#faq
It can't work with unsaved buffer.

**Comment by qifei9** [comment]
> Q: MPLS doesn't work with unsaved buffer.
>
> A: Yes, it's not. You have to save your buffer to make it work.

The FAQ only says about **MPLS** while I used **jedi**. Does it actually mean that both of MPLS and jedi do not work with unsaved buffer?

**Comment by avalonv** [comment]
@chemzqm could we please get an answer on the above question?

**Comment by chemzqm** [comment]
> Does it actually mean that both of MPLS and jedi do not work with unsaved buffer?

Should be both.
