### ISSUE TITLE
coc-settingds.json under the workspace .vim folder is not working

### ISSUE THREAD

**Issue by outshow** [neoclide/coc-python#96]
coc-settingds.json under the workspace .vim folder is not working.

setting with :CocLocalConfig is not working
setting with :CocConfig is working

**Comment by JoosepAlviste** [comment]
I think that this might be the same problem as I have in #95. I tried setting `"python.formatting.provider": "black"` for my project but got an error/warning that `autopep8` couldn't be found. Then set the same setting globally and `black` worked fine.

**Comment by outshow** [comment]
@JoosepAlviste yes, you are right.

**Comment by AllenDang** [comment]
Yes, I met the same problem here.
I cannot set pythonPath in workspace coc-config.

**Comment by chemzqm** [comment]
We don't support coc-settingds.json.

**Comment by AllenDang** [comment]
> We don't support coc-settingds.json.

Ok, then what's the proper way to set workspace python path?

**Comment by chemzqm** [comment]
Use `.vim/coc-settings.json`

**Comment by AllenDang** [comment]
> Use `.vim/coc-settings.json`

I think this issue is saying that setting python.pythonPath in .vim/coc-settings.json doesn't work.

**Comment by outshow** [comment]
> We don't support coc-settingds.json.

Sorry for my spelling mistake, it is coc-settings.json.
I put the coc-settings.json file in workspace path "/home/xx/workspace/py_test/.vim/"  and it does not work.
I put the same setting file in goable path "~/.vim/" and it works.

**Comment by chemzqm** [comment]
Should be fixed on latest coc.nvim release.
