### ISSUE TITLE
use a local mpls

### ISSUE THREAD

**Issue by teto** [neoclide/coc-python#97]
I have an MPLS already installed on my distribution, how can I ask coc-python to use that one instead of downloading its own version ?
thanks

**Comment by AllenDang** [comment]
Me too.

**Comment by esn89** [comment]
I am interested in this as well.  I also want to use the master branch version that I clone and build.

**Comment by kentac55** [comment]
I couldn't find how to use own version in coc-python.

But you can call mpls directly from coc.nvim.

`:CocConfig`

```json
{
  "diagnostic.displayByAle": true,
  "languageserver": {
    "mspyls": {
      "command": "dotnet",
      "args": [
        "exec",
        "/home/kc5m/src/github.com/microsoft/python-language-server/output/bin/Release/Microsoft.Python.LanguageServer.dll"
      ],
      "filetypes": [
        "python"
      ],
      "initializationOptions": {
        "testEnvironment": false,
        "analysisUpdates": true,
        "traceLogging": true,
        "asyncStartup": true
      }
    }
  }
}
```

**Comment by teto** [comment]
thanks I've moved away from coc-python. closing.
