### ISSUE TITLE
Function signature and docstring didn't show up when using autocomplete.

### ISSUE THREAD

**Issue by xiezhuojin** [neoclide/coc-python#98]
Coc-python server seems to be working but function signature and docstring didn't show up when using autocomplete. How can I fix it?

**Comment by benyaminl** [comment]
> Coc-python server seems to be working but function signature and docstring didn't show up when using autocomplete. How can I fix it?

anyscreenshoot or anything? like CocInfo?

**Comment by xiezhuojin** [comment]
![image](https://user-images.githubusercontent.com/37146118/67932537-0f186500-fbff-11e9-89dc-c9943d19d663.png)
Could this help?

**Comment by benyaminl** [comment]
> ![image](https://user-images.githubusercontent.com/37146118/67932537-0f186500-fbff-11e9-89dc-c9943d19d663.png)
> Could this help?

I think it should show up. 

![Screenshot_2019-11-12_10-34-55](https://user-images.githubusercontent.com/2817332/68639762-355fce00-0538-11ea-81df-dc1e4cf11d31.png)

**Comment by HansPinckaers** [comment]
I have the same problem. But it doesn't seem to be coc-python. Can you try commit 3aea9c96622ed7d0b31d6a221d552b6afe8c7a57 of coc.nvim? That is the last one that worked for me.

**Comment by HansPinckaers** [comment]
Please check latest master @chemzqm fixed this for me.

**Comment by xiezhuojin** [comment]
After upgraded my neovim, everything seem work fine. Thanks!
